-- INSERT DEFAULT USERS --
INSERT INTO USER(ID, NAME, PASSWORD, USER_ROLE) VALUES (1, 'ADMIN', '123456', 'ADMINISTRATOR');
INSERT INTO USER(ID, NAME, PASSWORD, USER_ROLE) VALUES (2, 'COMMON', '123456', 'COMMON');