CREATE SCHEMA IF NOT EXISTS CLIENT_APP;

CREATE TABLE CLIENT_APP.CLIENT
(
    ID         INTEGER      NOT NULL,
    CITY       VARCHAR(255) NOT NULL,
    COMPLEMENT VARCHAR(255),
    DISTRICT   VARCHAR(255) NOT NULL,
    STATE      VARCHAR(255) NOT NULL,
    STREET     VARCHAR(255) NOT NULL,
    ZIP_CODE   VARCHAR(255) NOT NULL,
    DOCUMENT   VARCHAR(255) NOT NULL,
    NAME       VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CLIENT_APP.CLIENT_EMAILS
(
    CLIENT_ID INTEGER NOT NULL,
    EMAILS    VARCHAR(255)
);

CREATE TABLE CLIENT_APP.PHONE
(
    ID        INTEGER NOT NULL,
    NUMBER    BIGINT,
    TYPE      INTEGER,
    CLIENT_ID INTEGER,
    PRIMARY KEY (ID)
);

CREATE TABLE CLIENT_APP.USER
(
    ID        INTEGER      NOT NULL,
    NAME      VARCHAR(255) NOT NULL,
    PASSWORD  VARCHAR(255) NOT NULL,
    USER_ROLE VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE CLIENT_APP.CLIENT_EMAILS
    ADD CONSTRAINT FKH10E3FOLE2B12YCVPEVWMH32H FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT;

ALTER TABLE CLIENT_APP.PHONE
    ADD CONSTRAINT FK3O48EC26LUJL3KF01HWQPLHN2 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT;